export const dispatchingBody = [
  { value: 'ssp/uf', label: 'SSP/UF' },
  { value: 'cartorio civil', label: 'Cartório Civil' },
  { value: 'policia federal', label: 'Polícia Federal' },
  { value: 'detran', label: 'DETRAN' },
  { value: 'cgpi/durex/dpf', label: 'CGPI/DUREX/DPF' },
  { value: 'cgpmaf', label: 'CGPMAF' },
  { value: 'detran', label: 'DETRAN' },
  { value: 'cnig', label: 'CNIG' },
  { value: 'cnt', label: 'CNT' },
  { value: 'coren', label: 'COREN' },
  { value: 'corecon', label: 'CORECON' },
  { value: 'cra', label: 'CRA' },
  { value: 'cras', label: 'CRAS' },
  { value: 'crb', label: 'CRB' },
  { value: 'crc', label: 'CRC' },
  { value: 'cre', label: 'CRE' },
  { value: 'crea', label: 'CREA' },
  { value: 'creci', label: 'CRECI' },
  { value: 'crefit', label: 'CREFIT' },
  { value: 'cress', label: 'CRESS' },
  { value: 'crf', label: 'CRF' },
  { value: 'crm', label: 'CRM' },
  { value: 'crn', label: 'CRN' },
  { value: 'cro', label: 'CRO' },
  { value: 'crp', label: 'CRP' },
  { value: 'CRPRE', label: 'CRPRE' },
  { value: 'crq', label: 'CRQ' },
  { value: 'CRRC', label: 'CRRC' },
  { value: 'crmv', label: 'CRMV' },
  { value: 'CSC', label: 'CSC' },
  { value: 'ctps', label: 'CTPS' },
  { value: 'dic', label: 'DIC' },
  { value: 'direx', label: 'DIREX' },
  { value: 'dpmaf', label: 'DPMAF' },
  { value: 'dpt', label: 'DPT' },
  { value: 'dst', label: 'DST' },
  { value: 'fgts', label: 'FGTS' },
  { value: 'FIPE', label: 'FIPE' },
  { value: 'fls', label: 'FLS' },
  { value: 'govgo', label: 'GOVGO' },
  { value: 'i cla', label: 'I CLA' },
  { value: 'ifp', label: 'IFP' },
  { value: 'igp', label: 'IGP' },
  { value: 'iiccecf/ro', label: 'IICCECF/RO' },
  { value: 'iimg', label: 'IIMG' },
  { value: 'iml', label: 'IML' },
  { value: 'ipc', label: 'IPC' },
  { value: 'ipf', label: 'IPF' },
  { value: 'mae', label: 'MAE' },
  { value: 'mex', label: 'MEX' },
  { value: 'mma', label: 'MMA' },
  { value: 'OAB', label: 'OAB' },
  { value: 'omb', label: 'OMB' },
  { value: 'pcmg', label: 'PCMG' },
  { value: 'pmmg', label: 'PMMG' },
  { value: 'pof/dpf', label: 'POF/DPF'},
  { value: 'pom', label: 'POM' },
  { value: 'sds', label: 'SDS' },
  { value: 'snj', label: 'SNJ' },
  { value: 'secc', label: 'SECC' },
  { value: 'sejusp', label: 'SEJUSP' },
  { value: 'ses/est', label: 'SES/EST' },
  { value: 'sesp', label: 'SESP' },
  { value: 'sjs', label: 'SJS' },
  { value: 'sjtc', label: 'SJTC' },
  { value: 'sjts', label: 'SJTS' },
  { value: 'sptc', label: 'SPTC' },
];

export const UF = [
  { value: 'ro', label:'RO' },
  { value: 'am', label:'AM' },
  { value: 'rr', label:'RR' },
  { value: 'pa', label:'PA' },
  { value: 'ap', label:'AP' },
  { value: 'to', label:'TO' },
  { value: 'ma', label:'MA' },
  { value: 'pi', label:'PI' },
  { value: 'ce', label:'CE' },
  { value: 'rn', label:'RN' },
  { value: 'pb', label:'PB' },
  { value: 'pe', label:'PE' },
  { value: 'se', label:'SE' },
  { value: 'ba', label:'BA' },
  { value: 'mg', label:'MG' },
  { value: 'es', label:'ES' },
  { value: 'rj', label:'RJ' },
  { value: 'sp', label:'SP' },
  { value: 'pr', label:'PR' },
  { value: 'sc', label:'SC' },
  { value: 'rs', label:'RS' },
  { value: 'MS', label:'MS' },
  { value: 'mt', label:'MT' },
  { value: 'go', label:'GO' },
  { value: 'df', label:'DF' },
  { value: 'ac', label:'AC' },
];
